### ISSUE TITLE
Expose Rust interface

### ISSUE THREAD

**Issue by farshed** [samizdatco/skia-canvas#205]
I'd like to use this as a renderer in a Rust project because it offers a nice abstraction on top of Skia and I would prefer not to recreate it myself.

Would you be open to exposing the drawing interface for use in Rust?

**Comment by samizdatco** [comment]
I'm totally open to the idea (enthusiastic even!), but it's a bigger task than it might initially seem. It would require decoupling all the routines that use `neon` to interact with javascript from the rust portions, and that separation is not as clean as it would be if this had been a goal since the beginning. Similarly, the interface offered by the rust 'core' isn't really designed for human use as much as simplifying the implementation of the javascript api it implements. The other thing that's a little tricky is dealing with the places where a persistent reference needs to be held (e.g., to the js Image backing a fill pattern) and creating rust equivalents for them.

The ideal solution would be to separate the rust portions of the project into two separate crates: `skia-canvas` (with the rust-only portions) and `skia-canvas-neon` (which imports the rust crate and contains just the neon interface code). If you'd like to take a stab at refactoring the library (the `src/context` directory would be a great place to start), I'd love to take a look at anything you come up with.

Either way, I'll definitely put it on the 'future directions' list though I don't currently have a concrete idea of when I'd be able to get to it.

**Comment by farshed** [comment]
Thanks for the breakdown. I’ll spend some time digging into the codebase to see how feasible it would be to refactor along those lines. If I come up with a rough proof of concept, I’ll share it here for feedback. 

Appreciate you adding this to the future directions list regardless!
