### ISSUE TITLE
Prebuilt binaries don’t support arm64 Linux (or Raspbian in particular)

### ISSUE THREAD

**Issue by PainOchoco** [samizdatco/skia-canvas#24]
I tried to install skia-canvas using NPM on my Raspberry Pi which run Raspbian but it failed.
Here is my NPM log: https://hastebin.com/uyodelilal.apache.

I noticed this specific line, seems like the AWS server which host skia-canvas is not reachable.
```
npm ERR! response status 403 Forbidden on https://skia-canvas.s3.us-east-1.amazonaws.com/v0.9.22/linux-arm-napi-v6.tar.gz
```

**Comment by samizdatco** [comment]
S3 may be claiming that it's a permissions error, but the real problem is that the `linux-arm-napi-v6.tar.gz` binaries don’t exist. For the moment, linux builds are x86-only I'm afraid.

It looks like arm-based builds will be coming in the next release though: https://github.com/rust-skia/rust-skia/pull/536

**Comment by samizdatco** [comment]
Raspbian builds (both 32 and 64 bit) have been added in version 0.9.26
