### ISSUE TITLE
Issue with rendering images and text

### ISSUE THREAD

**Issue by flazepe** [samizdatco/skia-canvas#34]
I have encountered an odd issue where images and text (might not be noticeable in the example picture) are rendered without any smoothing. I have tried changing the values of `ctx.imageSmoothingEnabled` and `ctx.imageSmoothingQuality` but to no avail.

Example code:
```js
(async () => {
	const { Canvas, loadImage } = require("skia-canvas");
	const canvas = new Canvas(420, 190);
	const ctx = canvas.getContext("2d");
	ctx.fillRect(0, 0, canvas.width, canvas.height);
	ctx.drawImage(
		await loadImage(
			"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Firefox_logo%2C_2019.svg/1200px-Firefox_logo%2C_2019.svg.png"
		),
		50,
		50,
		100,
		100
	);
	ctx.fillStyle = "#fff";
	ctx.font = "30px sans-serif";
	ctx.fillText("Hello world!", 180, 110);
	await canvas.png;
})();
```

Result (from `skia-canvas`):
![image](https://cdn.discordapp.com/attachments/732171142344736818/877334705136095282/file.png)

Expected result (from `canvas`):
![image](https://cdn.discordapp.com/attachments/732171142344736818/877334814104117279/file.png)

Platforms tried: Windows 10 (64-bit) and Ubuntu 20.04

**Comment by samizdatco** [comment]
Skia has some odd ideas internally about what the different [quality levels](https://github.com/google/skia/blob/0c12e32fad131c8e0e06a9aceb1a22015074f432/src/core/SkSamplingPriv.h#L18-L22) correspond to. In particular, it only uses mipmaps (which are important for downscaling applications like yours) if you set the quality to `medium`.

This doesn’t line up with the expected behavior for the context’s [`imageSmoothingQuality`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/imageSmoothingQuality) settings and should definitely be patched. But for now, you should be able to get better looking results when reducing image sizes if you add this to your code:

```js
ctx.imageSmoothingQuality = "medium"
```

**Comment by flazepe** [comment]
Images are fixed, but text are still the same (I'm guessing this issue is separate from `imageSmoothingQuality`). It's subtle, hopefully you can notice it.

Result (from `skia-canvas`):
![image](https://cdn.discordapp.com/attachments/732171142344736818/879349885827178526/unknown.png)

Expected result (from `canvas`):
![image](https://cdn.discordapp.com/attachments/732171142344736818/879349846014820402/unknown.png)
