### ISSUE TITLE
icudtl.dat access denied causes crash on Windows

### ISSUE THREAD

**Issue by dan-mba** [samizdatco/skia-canvas#35]
I am trying to migrate an app from node-canvas to skia-canvas.

I upgraded to 0.9.24 and now get the following error:
```
thread '<unnamed>' panicked at 'failed to write icudtl.dat into the current executable's directory: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\skia-bindings-0.41.0\src\icu.rs:15:10
note: run with 'RUST_BACKTRACE=1' environment variable to display a backtrace
```

I don't have a user runneradmin on my machine, so I'm assuming that directory is from the build machine.

**Comment by samizdatco** [comment]
The permissions problem is actually related to the folder where your nodejs exe lives (the `runneradmin` path is just part of the stack trace). The [ICU initialization code](https://github.com/rust-skia/rust-skia/blob/71c4728704abb4394077d5ea1b9faaf5c2ad5797/skia-bindings/src/icu.rs#L14-L15) checks to make sure that the `icudtl.dat` file exists in the same folder as your node interpreter and tries to create it if not. Can you check that your user has write permissions for that directory?

The non-short-term fix for this would be one of:
  1. modifying the ICU init routine to fall back to using the `icudtl.dat` file bundled with the module rather than panicking if it can’t place it next to the interpreter, or
  2. accepting the [draft pull request](https://github.com/rust-skia/rust-skia/pull/486) upstream that would do away with the need for the `icudtl.dat` file altogether

**Comment by samizdatco** [comment]
> In order to write to that, you need admin privileges.

That's way worse than the original (misleading) error message, no question. I'll roll back the change and start thinking about how to deal with the confusion the message keeps creating...
