### ISSUE TITLE
Text antialiasing is jaggy

### ISSUE THREAD

**Issue by flazepe** [samizdatco/skia-canvas#38]
#34 fixed images, but text are still the same (I'm guessing this issue is separate from `imageSmoothingQuality`). It's subtle, hopefully you can notice it.

Result (from `skia-canvas`):
![image](https://cdn.discordapp.com/attachments/732171142344736818/879349885827178526/unknown.png)

Expected result (from `canvas`):
![image](https://cdn.discordapp.com/attachments/732171142344736818/879349846014820402/unknown.png)

**Comment by flazepe** [comment]
Code, for reference:
```js
async function draw(skia) {
	const { Canvas, loadImage } = require(`${ skia ? "skia-" : ""}canvas`);
	const canvas = new Canvas(420, 190);
	const ctx = canvas.getContext("2d");
	ctx.fillStyle = "#fff";
	ctx.fillRect(0, 0, canvas.width, canvas.height);
	ctx.fillStyle = "#000";
	ctx.font = "bold 60px Segoe UI";
	ctx.fillText("Hello world!", 30, 110);
	require("fs").writeFileSync(`./image${skia ? "-skia": ""}.png`, skia ? await canvas.png : canvas.toBuffer());
}

draw();
draw(true);
```

**Comment by flazepe** [comment]
Code, for reference:
```js
async function draw(skia) {
	const { Canvas, loadImage } = require(`${skia ? "skia-" : ""}canvas`);
	const canvas = new Canvas(420, 190);
	const ctx = canvas.getContext("2d");
	ctx.fillStyle = "#fff";
	ctx.fillRect(0, 0, canvas.width, canvas.height);
	ctx.fillStyle = "#000";
	ctx.font = "bold 60px Segoe UI";
	ctx.fillText("Hello world!", 30, 110);
	require("fs").writeFileSync(`./image${skia ? "-skia": ""}.png`, skia ? await canvas.png : canvas.toBuffer());
}

draw();
draw(true);
```

**Comment by samizdatco** [comment]
Can you be a bit more specific about what you expected? I agree that the two images aren't pixel-identical but the Skia version *is* antialiasing text as far as I can reproduce:

<img width="1156" alt="image" src="https://user-images.githubusercontent.com/469523/130489540-075ca4c6-fbac-4816-a149-8b68ef25a177.png">

For more details about Skia's approach to antialiasing see: [The Raster Tragedy in Skia](https://skia.org/docs/dev/design/raster_tragedy/)

**Comment by flazepe** [comment]
It's the edges. `e`, `o`, and `!` is where it's noticeable the most. Is there a way to increase text "smoothing quality" like images?

![image](https://cdn.discordapp.com/attachments/732171142344736818/879499807427792976/unknown.png)

**Comment by samizdatco** [comment]
I think this has more to do with the fact that the type rasterizer is platform-dependent (whereas I believe node-canvas bundles its own and uses it everywhere) rather than anything Skia itself is doing in terms of compositing. Note how the weight varies based on OS:

#### macOS
<img width="450" alt="mac" src="https://user-images.githubusercontent.com/469523/130676939-02c19da5-2bb6-49dd-941c-c8d1a85a6faf.png">

#### Linux
<img width="450" alt="linux" src="https://user-images.githubusercontent.com/469523/130676948-341bf157-ec0e-4277-8456-0cd9effc23d4.png">

The antialiasing definitely looks smoother than your example in both these cases:

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/469523/130677639-4ec3b8d0-c615-4b2e-bc42-d0f451652372.png">

Are you running on Windows by any chance?

**Comment by flazepe** [comment]
Yes, I'm running on Windows. Here's an actual comparison (where I initially found the issue), on Linux:

`skia-canvas`:
![image](https://cdn.discordapp.com/attachments/732171142344736818/879857577503100928/file.png)

`canvas`:
![image](https://cdn.discordapp.com/attachments/732171142344736818/867511652651892756/file.png)

**Comment by flazepe** [comment]
If there's no fix, I'd probably be fine with it. It's not that noticeable.
