### ISSUE TITLE
width-variable is reserved for skia-canvas, is it a bug or a feature?

### ISSUE THREAD

**Issue by ProgrammingLife** [samizdatco/skia-canvas#61]
Tried to change this working code:
```
const canvas = new Canvas( 1920, 1080 )
const ctx = canvas.getContext( "2d" )
const { width, height } = canvas
```
to this:
```
const canvas = new Canvas( 1920, 1080 )
const ctx = canvas.getContext( "2d" )
const { canvas_width, height } = canvas // renamed here
```

And I got broken code with the message:
```
» tsc && node dist/test.js
/home/user/nodejs/node_modules/skia-canvas/lib/index.js:54
    return this.native[fn](this[ø], ...args)
                          ^
TypeError: x must be a number
    at CanvasRenderingContext2D.ƒ (/home/user/nodejs/node_modules/skia-canvas/lib/index.js:54:27)
    at CanvasRenderingContext2D.fillText (/home/user/nodejs/node_modules/skia-canvas/lib/index.js:410:10)
    at start (/home/user/path/test.js:56:13)
Node.js v17.0.1
```

If I rename it back - all work fine again.
Is it a bug or a feature?

**Comment by samizdatco** [comment]
I think you'll find that the `canvas_width` variable you created has the value `undefined` since the canvas object doesn't have an attribute with that name. Here's how you rename values when using [destructuring assignment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#assigning_to_new_variable_names).

You're getting an error from `fillText()` because it expected a number rather than undefined.

**Comment by ProgrammingLife** [comment]
@samizdatco, omg shame on me. I need more rest. 😀 Thank you for the reply!
