### ISSUE TITLE
Perspective transforms image smoothing not working properly

### ISSUE THREAD

**Issue by ewanhowell5195** [samizdatco/skia-canvas#85]
Left image produced using skia-canvas, right image using ImageMagick
![comparison](https://user-images.githubusercontent.com/48070995/153315035-95f6d680-373b-48aa-b975-cf1fbfd523bd.png)
The outer edge of the image seems to work correctly however

Changing the imageSmoothingQuality doesn't seem to improve anything

This doesn't seem to affect drawing things like rectangles and text, only images and canvases
![out](https://user-images.githubusercontent.com/48070995/153315126-b720d23b-1f77-4f02-aac4-8ed88e430050.png)

The higher resolution the input image, the worse it gets

256x265 input image
![squares](https://user-images.githubusercontent.com/48070995/153315427-053e03d9-1868-49d1-bd28-dfeadcb165dc.png)
![out](https://user-images.githubusercontent.com/48070995/153315431-43de6da0-4438-42d8-bbf7-66873888353e.png)

1024x1024 input image
![squares](https://user-images.githubusercontent.com/48070995/153315361-7080b7e3-9120-4d78-ad04-49b062701850.png)
![out](https://user-images.githubusercontent.com/48070995/153315394-bed1b8e8-f61d-47b8-b1f6-686126273887.png)

Code i tested with:
```js
import {Canvas, loadImage} from "skia-canvas"

const img = await loadImage("squares.png")

const canvas = new Canvas(256, 256)
const ctx = canvas.getContext("2d")

ctx.setTransform(ctx.createProjection([65, 10, 212, 112, 250, 200, 0, 256]))

ctx.imageSmoothingQuality = "high"

ctx.drawImage(img, 0, 0, canvas.width, canvas.height)

canvas.saveAs("out.png")
```

**Comment by samizdatco** [comment]
This seems to be a known issue with Skia itself—specifically that it doesn't use a high-quality image filter when downscaling images, despite doing so when upscaling. I've tried fiddling with the [SamplingOptions](https://github.com/samizdatco/skia-canvas/blob/4c8cec6ae5f6bb911d9b1d9c34692bdb36ec99b7/src/utils.rs#L516-L533) values that are used for the different `imageSmoothingQuality` settings, but (as described in [this discussion](https://groups.google.com/g/skia-discuss/c/2du6tuE3eds/m/2rSEyJsvBAAJ) and [this one](https://groups.google.com/g/skia-discuss/c/VUXCB_PReWI)) the cubic resampler is only applied when upsampling. Unfortunately, enabling bi-linear filtering didn't have a noticeable effect against your sample code.

SkiaSharp has also been wrestling with the [for some time](https://github.com/mono/SkiaSharp.Extended/issues/102).

So if there is a solution to this problem, it's going to be more complicated. Some possibilities that might be worth investigating:
  1. Using GPU-backed rendering (which, I believe, is why these artifacts aren't seen in Chrome)
  2. Applying transforms using an [ImageFilter](https://github.com/rust-skia/rust-skia/blob/cfcca61870bc5554c1335a44f9db9f0f7d9d7937/skia-safe/src/effects/image_filters.rs#L311) rather than leaving that to the canvas
  3. Manually applying a convolution when downscaling images (as [suggested here](https://github.com/mono/SkiaSharp/issues/520#issuecomment-444973518))

In the meantime, the best workaround might be to generate an interim bitmap of your canvas at a higher resolution (e.g., using 3 or 4 for the [`density`](https://github.com/samizdatco/skia-canvas/#density) export argument), then scale that image down to your desired size:

```js
const img = await loadImage("squares.png")
const canvas = new Canvas(256, 256)
const ctx = canvas.getContext("2d")

ctx.setTransform(ctx.createProjection([65, 10, 212, 112, 250, 200, 0, 256]))
ctx.drawImage(img, 0, 0, canvas.width, canvas.height)
let snapshot = await canvas.toBuffer('png', {density:4})

ctx.clearRect(0, 0, canvas.width, canvas.height)
ctx.resetTransform()
ctx.drawImage(await loadImage(snapshot), 0, 0, canvas.width, canvas.height)
canvas.saveAs("out.png")
```
<img width="256" alt="out@2x" src="https://user-images.githubusercontent.com/469523/153718504-caf7950e-7f16-466b-b0a3-a49f7a605fd0.png">
